[rom]
title = "WoodyBoy"
short-title = "WB"
category = "APPLET_GAME"
default-locale = "en"
copyright = """\
Copyright (c) 2018-2025 Mahyar Koshkouei
Copyright (c) 2024-2025 dogtopus
SPDX-License-Identifier: MIT\
"""
version = "1.3.1"

[metadata.en]
title = "WoodyBoy"
short-title = "WB"
