[rom]
title = "WoodyBoy Color"
short-title = "WBC"
category = "APPLET_GAME"
default-locale = "en"
copyright = """\
Copyright (c) 2018-2025 Mahyar Koshkouei
Copyright (c) 2024-2025 dogtopus
SPDX-License-Identifier: MIT\
"""
version = "1.4.0"

[metadata.en]
title = "WoodyBoy Color"
short-title = "WBC"
